config/routes.rb
Rails.application.routes.draw do

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'

  get '/top' => 'homes#top'
  
  get 'posts/search' => 'posts#search'
  
  resources :users
  resources :posts do
    resources :reservations
    post 'reservations/confirm' => 'reservations#confirm'
    post 'reservations/back' => 'reservations#back'
    
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  mount_uploader :image, RoomPicsUploader
  
  validates :roomname, presence:true
  validates :introduction, length: { in: 10..100 }
  validates :price, numericality: true
  validates :address, presence:true
  validates :image, presence: { message: 'をアップロードしてください' }

  belongs_to :user
  has_many :reservations
end

app/models/reservation.rb
class Reservation < ApplicationRecord
  validates_acceptance_of :confirming
  validates :start_date, presence: true
  validate :start_date_cannot_be_in_the_past
  def start_date_cannot_be_in_the_past
    if start_date.present? && start_date < Date.today
      errors.add(:start_date, "は本日以降の日付を入力してください")
    end
  end
  validates :finish_date, presence: true
  validate :start_end_check
  def start_end_check
    errors.add(:finish_date, "はチェックインより過去の日付は登録できません") unless
    self.start_date <= self.finish_date 
  end
  validates :ppl, numericality: {only_integer: true, greater_than: 0, message:"を入力してください"}

  belongs_to :user
  belongs_to :post
end

app/models/user.rb
class User < ApplicationRecord
  
  mount_uploader :image, UserImageUploader
  validates :name, presence:true
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, format: { with: VALID_EMAIL_REGEX , message: 'は@を付けた形で入力してください' }
  has_secure_password
  validates :password, length: {minimum: 6, message: 'は必ず6文字以上で入力してください'}
  

  has_many :posts
  has_many :reservations
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper
  helper_method :current_user
  before_action :login_required

  private

  def current_user
    @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id]
  end

  def login_required
    redirect_to login_path unless current_user
  end
    
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  skip_before_action :login_required
  def top
    @q = Post.ransack(params[:q])
    @posts = @q.result
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  skip_before_action :login_required, only:[:search, :show]

  def index #ユーザがポストしたものを一覧表示
    @posts = current_user.posts
  end

  def new #ポスト(ルーム)を新規登録
    @post = Post.new
  end
  
  def create # ポストをDBに登録
    @post = current_user.posts.new(post_params)
    if @post.save
      flash[:notice] = "新しいルームを登録しました"
      redirect_to ("/posts/#{@post.id}")
    else
      render "posts/new"
    end
  end

  def show # 登録したポストを表示（個人）
    @post = Post.find(params[:id])
  end

  def search
    @q = Post.ransack(params[:q])
    @posts = @q.result
  end

  def edit
    @post = current_user.posts.find(params[:id])
  end

  def update
    @post = current_user.posts.find(params[:id])
    if @post.update(post_params)
      flash[:notice] = "ルーム情報を更新しました"
      redirect_to @post
    else
      render "edit"
    end
  end

  def destroy
    @post = current_user.posts.find(params[:id])
    @post.destroy
    flash[:notice] = "ルーム登録を削除しました"
    redirect_to :posts
  end

  private
  def post_params
    params.require(:post).permit(:roomname, :introduction, :price, :address, :image)
  end

end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
	before_action :reservation_params, only: [:confirm]

  def index
		@reservations = Reservation.where(user_id: current_user.id)
	end

	def new
		@reservation = Reservation.new
		@post = params[:post_id]
	end

	def back
		@reservation = current_user.reservations.new(reservation_params)
		@post = params[:post_id]
		render :new
	end

	def confirm
		@reservation = current_user.reservations.new(reservation_params)
		@post = params[:post_id]
		@reservation.post_id = @post
		if @reservation.invalid?
			render :new
		end
	end

	def create
		@reservation = current_user.reservations.new(reservation_params)
		@post = params[:post_id]
		@reservation.post_id = @post
		if @reservation.save
      flash[:notice] = "予約が完了しました。"	
      redirect_to post_reservations_path
		else
			render :new
		end
	end

  def show
    @reservation = current_user.reservations.find(params[:id])
		@post = @reservation.post
	end

	def destroy
		@reservation = current_user.reservations.find(params[:id])
		@post = params[:post_id]
		@reservation.destroy
		flash[:notice] = "予約をキャンセルしました"
		redirect_to post_reservations_path
	end


	private

	def reservation_params
		params.require(:reservation).permit(:id, :start_date, :finish_date, :ppl, :user_id, :post_id)
	end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :login_required

#ログイン処理
  def create
    user=User.find_by(email: session_params[:email])
    if user&.authenticate(session_params[:password])
      session[:user_id]=user.id
      redirect_to ('/top')
    else
      flash.now[:notice] = 'メールアドレスかパスワードが間違っています。'
      render 'new'
    end
  end

#ログアウト処理
  def destroy
    reset_session
    redirect_to ('/top')
  end

  private

  def session_params
    params.require(:session).permit(:email, :password)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :login_required, only: [:new, :create]

  def new #新規ユーザーアカウントを作る
    @user = User.new
  end

  def create #ユーザーをDBに登録する
    @user = User.new(user_params)
    if @user.save
      log_in @user
      flash[:notice] = "アカウントが登録されました"
      redirect_to ("/users/#{@user.id}")
    else
      render "users/new"
    end
  end

  def show #個人ユーザー情報
    @user = User.find_by(id:session[:user_id])
  end

  def edit #個人ユーザー情報の編集
    @user = User.find_by(id:session[:user_id])
  end

  def update #個人ユーザー情報の更新
    @user = User.find(params[:id])
      if @user.update(user_params)
        flash[:notice] = "情報を更新されました"
        redirect_to ("/users/#{@user.id}")
      else
        render "edit"
      end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :image)
  end

end

app/helpers/sessions_helper.rb
module SessionsHelper
  # 渡されたユーザーでログインする
  def log_in(user)
    session[:user_id] = user.id
  end

  # 現在ログイン中のユーザーを返す（いる場合）
  def current_user
    if session[:user_id]
      @current_user ||= User.find_by(id: session[:user_id])
    end
  end

  #受け取ったユーザーがログイン中のユーザーと一致すれば true を返す
  def current_user?(user)
    user == current_user
  end

  # ユーザーがログインしていれば true、その他なら false を返す
  def logged_in?
    !current_user.nil?
  end

  # 現在のユーザーをログアウトする
  def log_out
    session.delete(:user_id)
    @current_user = nil
  end
end

app/views/homes/top.html.erb
<body>
  <div class="top">
    <div class="container-top">
      <div class="search">
        <div class="search-box">
          <h2 class="main-sentence">Wherever you want to go..</h2>
          <p>Where would you like to travel?</p>
          <%= search_form_for @q, url: '/posts/search' do |f| %>
            <div class="area">
              <%= f.label :address, "Area...✈︎" %>
              <%= f.search_field :address_cont %></br>
            </div>
            <div class="freeword">
              <%= f.label :roomname_or_introduction_or_price_or_address_gt, "Keyword...✈︎" %>
              <%= f.search_field :roomname_or_introduction_or_price_or_address_cont %></br>
            </div>
            <div class="button-top">
              <%= f.submit 'S E A R C H', :class => "top-btn" %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  
    <div class="recommendations">
      <h1>おすすめエリア</h1>
      <div class="item-box">
        <span>Tokyo</span>
        <a href="http://localhost:3000/posts/search?q%5Baddress_cont%5D=%E6%9D%B1%E4%BA%AC&q%5Broomname_or_introduction_or_price_or_address_cont%5D=&commit=%E6%A4%9C%E7%B4%A2">
        <img src="/assets/img_tokyo.jpg", class="panel-image">
        </a>
      </div>
      <div class="item-box">
        <span>Osaka</span>
        <a href="http://localhost:3000/posts/search?q%5Baddress_cont%5D=%E5%A4%A7%E9%98%AA&q%5Broomname_or_introduction_or_price_or_address_cont%5D=&commit=%E6%A4%9C%E7%B4%A2">
        <img src="/assets/img_osaka.jpg", class="panel-image">
        </a>
      </div>
      <div class="item-box">
        <span>Kyoto</span>
        <a href="http://localhost:3000/posts/search?q%5Baddress_cont%5D=%E4%BA%AC%E9%83%BD%E5%BA%9C&q%5Broomname_or_introduction_or_price_or_address_cont%5D=&commit=%E6%A4%9C%E7%B4%A2">
        <img src="/assets/img_kyoto.jpg", class="panel-image">
        </a>
      </div>
      <div class="item-box">
        <span style="font-size : 40px">Sapporo</span>
        <a href="http://localhost:3000/posts/search?q%5Baddress_cont%5D=%E6%9C%AD%E5%B9%8C&q%5Broomname_or_introduction_or_price_or_address_cont%5D=&commit=%E6%A4%9C%E7%B4%A2">
        <img src="/assets/img_sapporo.jpg", class="panel-image">
        </a>
      </div>
    </div>
  </div>
</body>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <header>
    <title>Shareapp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag "application", media: 'all', 'data-turbolinks-track': 'reload'%>
    <meta name="viewport" content="width=device-width,initial-scale=1,shrink-to-fit=no">
  </head>

  <body>
    <header>
      <% if logged_in? %>
        <%= render 'users/logged_in' %>
      <% else %>
        <%= render 'users/not_logged_in' %>
      <% end %>
    </header>

    <%= yield %>
    
    <footer>
      <h3>@ 2021 one of asainment</h3>
    </footer>
  </body>
</html>

app/views/posts/edit.html.erb
<div class="main-box">
  <div class="post-container">
    <h1>ルーム情報の編集</h1>
    
    <%= form_with model: @post do |f| %>
      <table>
        <tr>
          <th><%= f.label :roomname ,"ルーム名" %></th>
          <td><%= f.text_field :roomname, size: "31x10" %></td>
        </tr>
        <tr>
          <th><%= f.label :introduction ,"ルーム紹介" %></th>
          <td><%= f.text_area :introduction, size: "30x10" %></td>
        </tr>
        <tr>
          <th><%= f.label :price ,"料金（１泊）" %></th>
          <td><%= f.text_field :price, size: "31x10" %></td>
        </tr>
        <tr>
          <th><%= f.label :address ,"住所" %></th>
          <td><%= f.text_field :address, size: "31x10" %></td>
        </tr>
        <tr>
          <th><%= f.label :image, 'ルーム画像' %></th>
          <td><%= f.file_field :image, accept: 'image/jpeg,image/gif,image/png' %></td>
        </tr>
      </table>
      <div class="button">
        <ul>
          <li><%= f.submit "編集を完了する", :class => "btn" %></li>
        </ul>
      </div>
    <% end %>
  </div>
</div>

app/views/posts/index.html.erb
<div class="main-box">
  <% if flash[:notice] %>
    <p class="notice"><%= flash[:notice] %></p>
  <% end %>

  <div class="post-index-container">
    <h1>登録ルーム一覧</h1>
    <table class="yoko">
      <thead>
        <tr>
          <th class="room-img">ルーム画像</th>
          <th class="roomname">ルーム名</th>
          <th class="price">値段<br>（１泊）</th>
          <th class="introduce">ルーム詳細</th>
          <th class="edit">編集</th>
          <!-- <th>削除</th> -->
        </tr>
      </thead>

      <tbody>
        <% @posts.each do |post| %>
          <tr>
            <td><%= image_tag post.image.to_s, size: '220x150' %></td>
            <td><%= post.roomname %></td>
            <td><%= post.price %>円</td>
            <td><%= link_to "more..", post %></td>
            <td><%= link_to "編集", [:edit, post] %></td>
            <!-- <td><%#= button_to "削除", post, method: :delete, data: { confirm: "本当に削除しますか？" } %></td> -->
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/posts/new.html.erb
<div class="main-box">
  <div class="post-container">
    <h1>ルーム登録</h1>
    <p>※全て必須になります。</p>
    <%= render "shared/error", obj: @post %>

    <%= form_with model: @post, local: true do |f| %>
      <table class="box">
        <tr>
          <th><%= f.label :roomname ,"ルーム名" %></th>
          <td><%= f.text_field :roomname, size: "40x10", :placeholder => "ルーム名を入力" %></td>
        </tr>

        <tr>
          <th><%= f.label :introduction ,"ルーム紹介" %></th>
          <td><%= f.text_area :introduction, size: "40x10", :placeholder => "ルームの説明を入力" %></td>
        </tr>

        <tr>
          <th><%= f.label :price ,"料金" %></th>
          <td><%= f.text_field :price, size: "40x10", :placeholder => "１人/1泊の料金を入力" %></td>
        </tr>

        <tr>
          <th><%= f.label :address ,"住所" %></th>
          <td><%= f.text_field :address, size: "40x10", :placeholder => "県名から住所を入力" %></td>
        </tr>

        <tr>
          <th><%= f.label :image, 'ルーム画像' %></th>
          <td><%= f.file_field :image, accept: 'image/jpeg,image/gif,image/png' %></td>
        </tr>
      </table>  
      <div class="button">
        <tr>
          <%= f.submit "登録する", :class => "btn" %>
        </tr>
      </div>
    <% end %>
  </div>
</div>

app/views/posts/search.html.erb
<div class="main-box">
  <div class="result-container">
    <h1>検索結果</h1>
    <div class="result-box">

      <table>
        <tbody>
          <% @posts.each do |post| %>
            <div class="result">
              <div class="inside">
                <%= image_tag post.image_url, size: '300x200' %><br>
                <%= link_to post, method: :get do %> 
                  ルーム名：<%= post.roomname %><br>住所：<%= post.address %>
                <% end %> 
              </div>
            </div>
          <% end %>
        </tbody>
      </table>

    </div>
  </div>
</div>

app/views/posts/show.html.erb
<div class="main-box">
  <% if flash[:notice] %>
    <p class="notice"><%= flash[:notice] %></p>
  <% end %>
  
  <div class="post-show-container">
    <h1>ルーム詳細</h1>
    
    <table>
      <tr>
        <th class="room">ルーム画像</th>
        <td><%= image_tag @post.image_url, size: '300x200' %></td>
      </tr>
      <tr>
        <th>ルーム名</th>
        <td><%= @post.roomname %></td>
      </tr>
      <tr>
        <th>ルーム紹介</th>
        <td><%= @post.introduction %></td>
      </tr>
      <tr>
        <th>住所</th>
        <td><%= @post.address %></td>
      </tr>
      <tr>
        <th>料金</th>
        <td><%= @post.price %>円</td>
      </tr>
      <tr>
        <th>ルーム登録日</th>
        <td><%= @post.created_at.to_s(:datetime_jp) %></td>
      </tr>
      <tr>
        <th>予約</th>
        <td><%= link_to "→ こちらから ←", "/posts/#{@post.id}/reservations/new" %></td>
      </tr>
    </table>
  </div>
</div>

app/views/reservations/confirm.html.erb
<div class="main-box">
  <div class="reservation-container">
    <h1>予約フォーム</h1>

    <table>
      <tr>
        <th>ルーム名</th>
        <td><%= @reservation.post.roomname %></td>
      </tr>
      <tr>
        <th>チェックイン</th>
        <td><%= @reservation.start_date.to_s(:datetime_jp) %></td>
      </tr>
      <tr>
        <th>チェックアウト</th>
        <td><%= @reservation.finish_date.to_s(:datetime_jp) %></td>
      </tr>
      <tr>
        <th>宿泊日数</th>
        <td><%= @sum = ((@reservation.finish_date - @reservation.start_date)/ 86400).to_int %>日</td>
      </tr>
      <tr>
        <th>料金（１泊）</th>
        <td><%= @reservation.post.price %>円</td>
      </tr>
      <tr>
        <th>人数</th> 
        <td><%= @reservation.ppl %>人</td>
      </tr>
      <tr>
        <th>合計料金</th>
        <td><%= ((@reservation.post.price * @reservation.ppl)* @sum) %>円</td>
      </tr>
    </table>

    <div class="buttons">
      <%= form_with model: @reservation, method: :post, url: post_reservations_back_path(@post), local: true, :class => "button-back" do |form| %>
        <%= form.hidden_field :start_date %>
        <%= form.hidden_field :finish_date %>
        <%= form.hidden_field :ppl %>
        <div>
          <ul>
            <%= form.submit '入力画面に戻る', :class => "btn-back" %>
          </ul>
        </div>
      <% end %>

      <%= form_with model: @reservation, method: :post, url: post_reservations_path, local: true, :class => "button-reservation" do |form| %>
        <%= form.hidden_field :start_date %>
        <%= form.hidden_field :finish_date %>
        <%= form.hidden_field :ppl %>
        <div>
          <ul>
            <%= form.submit '予約を確定する', :class => "btn-confirm" %>
          </ul>
        </div>
      <% end %>
    </div>

  </div>
</div>

app/views/reservations/index.html.erb
<div class="main-box">
  <% if flash[:notice] %>
    <p class="notice"><%= flash[:notice] %></p>
  <% end %>

  <div class="reservation-index-container">
    <h1>予約一覧</h1>
    
    <table class="yoko">
      <thead>
        <tr>
          <th class="room-img">ルーム画像</th>
          <th class="roomname">ルーム名</th>
          <th class="date">チェック<br>イン</th>
          <th class="date">チェック<br>アウト</th>
          <th class="book">予約<br>詳細</th>
        </tr>
      </thead>

      <tbody>
        <% @reservations.each do |reservation| %>
          <tr>
            <td><%= image_tag reservation.post.image.to_s, size: '220x150' %></td>
            <td><%= reservation.post.roomname %></td>
            <td><%= reservation.start_date.to_s(:datetime_jp) %></td>
            <td><%= reservation.finish_date.to_s(:datetime_jp) %></td>
            <td><%= link_to "more..", post_reservation_path(reservation.post.id,reservation.id) %></td>
          </tr>   
        <% end %>
      </tbody>
    </table>
    
  </div>
</div>

app/views/reservations/new.html.erb
<div class="main-box">
  <div class="reservation-container">
    <h1>予約フォーム</h1>

    <%= render "shared/error", obj: @reservation %>

    <%= form_with model:@reservation, method: :post, url: post_reservations_confirm_path(@post), local: true do |f| %>    
      <table class="box">
        <tr>
          <th>チェックイン</th>
          <td><%= f.date_select :start_date, class: 'form-control' %></td>
        </tr>
        <tr>
          <th>チェックアウト</th>
          <td><%= f.date_select :finish_date, class: 'form-control' %></td>
        </tr>
        <tr>
          <th>人数</th>
          <td><%= f.text_field :ppl %></td>
        </tr>
      </table>
      
      <div class="button">
        <ul>
          <%= f.submit '確認画面へ', :class => "btn" %>
        </ul>
      </div>
    <% end %>
    
  </div>
</div>

app/views/reservations/show.html.erb
<div class="main-box">
  <div class="reservation-show-container">
    <h1>予約詳細</h1>

    <table>
      <tr>
        <th>ルーム名/ルーム画像</th>
        <td><%= link_to @post.roomname , "/posts/#{@post.id}" %><br>
        <%= image_tag @post.image.to_s, width: 250 %></td>
      </tr>
      <tr>
        <th>チェックイン</th>
        <td><%= @reservation.start_date.to_s(:datetime_jp) %></td>
      </tr>
      <tr>
        <th>チェクアウト</th>
        <td><%= @reservation.finish_date.to_s(:datetime_jp) %></td>
      </tr>
      <tr>
        <th>人数</th>
        <td><%= @reservation.ppl %>人</td>
      </tr>
      <tr>
        <th>料金（１泊）</th>
        <td><%= @post.price %>円</td>
      </tr>
      <tr>
        <th>宿泊日数</th>
        <td><%= @sum = ((@reservation.finish_date - @reservation.start_date)/ 86400).to_int %>日</td>
      </tr>
      <tr>
        <th>合計料金</th>
        <td><%= ((@post.price * @reservation.ppl)* @sum) %>円</td>
      </tr>
      <tr>
        <th>予約確定日</th>
        <td><%= @reservation.created_at.to_s(:datetime_jp) %></td>
      </tr>
    </table>
  
    <div class="C-button">
      <tr>
        <%= button_to "この予約をキャンセルする", "/posts/#{@post.id}/reservations/#{@reservation.id}", method: :delete, :class => "btn" %>
      </tr>
    </div>
    
  </div>
</div>

app/views/shared/_error.html.erb
<% if obj.errors.any? %>
  <% obj.errors.full_messages.each do |message| %>
    <ul>
      <li><%= message %></li>
    </ul>
  <% end %>
<% end %>

app/views/users/_logged_in.html.erb
<div class="header-bar">
  <div class="logo">
    <a href="/top">poteshare</a>
  </div>

  <div class="menu-pc">
    <nav>
      <ul>
        <li><%= link_to "ルーム登録", '/posts/new' %></li>
        <li><%= link_to "登録ルーム一覧", '/posts' %></li>
        <li><%= link_to "予約一覧", '/posts/1/reservations' %></li>
        <li><%= link_to "プロフィール", current_user %></li>
        <li><%= link_to "ログアウト", '/logout' %></li>
      </ul>
    </nav>
  </div>

  <div class="menu-phone">
    <input type="checkbox" id="menu">
    <label for="menu"><div class="line"></div><div class="line"></div><div class="line"></div></label>
    <div id="content">
      <nav class="content-phone">
        <ul>
          <li><%= link_to "ルーム登録", '/posts/new' %></li>
          <li><%= link_to "登録ルーム一覧", '/posts' %></li>
          <li><%= link_to "予約一覧", '/posts/1/reservations' %></li>
          <li><%= link_to "プロフィール", current_user %></li>
          <li><%= link_to "ログアウト", '/logout' %></li>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/users/_not_logged_in.html.erb
<header>
  <div class="header-bar">
    <div class="logo">
      <a href="/top">poteshare</a>
    </div>
    <nav class="header-nav">
      <ul>
        <li><a class="login-btn" href="/login">ログイン</a></li>
        <li><a class="new-btn" href="/users/new">新規登録</a></li>
      </ul>
    </nav>
  </div>
</header>

app/views/users/edit.html.erb
<div class="main-box">
  <div class="user-container">
    <h1>アカウント編集</h1>

    <%= render "shared/error", obj: @user %>

    <%= form_with model: @user do |f| %>
      <table class="box">
        <div class="inputs">
          <tr>
            <th><%= f.label :image ,"プロフィール画像" %></th>
            <td>
              <% if @user.image? %>
                <%= image_tag @user.image.thumb.url, size: '150x150', :class => "account-img" %>
              <% else %>
                <%= image_tag "/assets/initialimage.jpg", size: '150x150', :class => "account-img" %>
              <% end %>
                <%= f.file_field :image, accept: 'image/jpeg,image/gif,image/png' %>
            </td>
          </tr>
          <tr>
            <th><%= f.label :name ,"名前" %></th>
            <td><%= f.text_field :name, size: "40x10" %></td>
          </tr>
          <tr>
            <th class="email"><%= f.label :email ,"メールアドレス" %></th>
            <td><%= f.text_field :email, size: "40x10" %></td>
          </tr>
          <tr>
            <th><%= f.label :password ,"新しいパスワード" %></th>
            <td><%= f.password_field :password, size: "40x10" %></td>
          </tr>
          <tr>
            <th><%= f.label :password_confirmation, "新しいパスワード （確認用）" %></th>
            <td><%= f.password_field :password_confirmation, size: "40x10" %></td>
          </tr>
          <tr>
            <th><%= f.label :password ,"現在のパスワード" %></th>
            <td><%= f.password_field :password, size: "40x10" %></td>
          </tr>
        </div>
      </table>
      
      <div class="button">
        <ul>
          <li><%= f.submit "更新する", :class => "btn" %></li>
        </ul>
      </div>
    <% end %>
  </div>
</div>

app/views/users/new.html.erb
<div class="main-box"> 
  <div class="signin">
    <%= render "shared/error", obj: @user %>

    <div class="signin-container">
      <h2>アカウント作成</h2>
      <p>必要な情報を入力してください。<br> ※全て必須になります。</p>

      <div class="box">
        <%= form_with model: @user, local: true do |f| %>
          <div class="inputs">
            <tr>
              <%= f.label :name ,"名前" %><br>
              <%= f.text_field :name %>
            </tr><br>
            <tr>
              <%= f.label :email ,"メールアドレス" %><br>
              <%= f.text_field :email %>
            </tr><br>
            <tr>
              <%= f.label :password ,"パスワード" %><br>
              <%= f.password_field :password %>
            </tr><br>
            <tr>
              <%= f.label :password_confirmation, "パスワード（確認用）" %><br>
              <%= f.password_field :password_confirmation %>
            </tr>
          </div>
          
          <div class="button-top">
            <%= f.submit "アカウントを作る", :class => "btn" %><br>
            <%= link_to "既にアカウントをお持ちの方", '/login' %>
          </div>
        <% end %>
      </div>

    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="main-box">
  <% if flash[:notice] %>
    <p class="notice"><%= flash[:notice] %></p>
  <% end %>
  
  <div class="user-container">
    <h1>アカウント詳細</h1>
    <div class="user-show-box">
      <div class="account-image">
        <% if @user.image? %>
          <%= image_tag @user.image.thumb.url, size: '150x150', :class => "account-img" %>
        <% else %>
          <%= image_tag "/assets/initialimage.jpg", size: '150x150', :class => "account-img" %>
        <% end %>
      </div>
      <table>
        <tr>
          <th>名前</th>
          <td><%= @user.name %></td>
        </tr>
        <tr>
          <th>メールアドレス</th>
          <td><%= @user.email %></td>
        </tr>
      </table>
    </div>
    
    <div>
      <ul class="user-show">
        <li><%= link_to "情報を編集する", "/users/#{@user.id}/edit" %></li>
      </ul>
    </div>
    
  </div>
</div> 